import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../app_date_picker.dart';
import '../../providers/app_provider.dart';
import '../../utils/theme_constants.dart';
import 'package:provider/provider.dart';

class PurchaseHeader extends StatelessWidget {
  final String entryNo;
  final Widget entryNavBox;
  final int paymentMode;
  final ValueChanged<int> onPaymentModeChanged;
  final TextEditingController supplierCtrl;
  final FocusNode supplierFocus;
  final LayerLink supplierLayer;
  final ValueChanged<String> onSupplierChanged;
  final DateTime dueDate;
  final ValueChanged<DateTime> onDueDateChanged;
  final TextEditingController doneByCtrl;
  final FocusNode doneByFocus;
  final LayerLink doneByLayer;
  final ValueChanged<String> onDoneByChanged;
  final int gstMode;
  final ValueChanged<int> onGstModeChanged;
  final DateTime date;
  final ValueChanged<DateTime> onDateChanged;
  final DateTime supInvDate;
  final ValueChanged<DateTime> onSupInvDateChanged;
  final TextEditingController supInvNoCtrl;
  final FocusNode supInvNoFocus;
  final bool isAutoGeneratedSupInv;
  final bool isDuplicateSupInv;
  final ValueChanged<String>? onSupInvNoChanged;
  final TextEditingController invTotalCtrl;
  final FocusNode invTotalFocus;
  
  final Widget formatSelector;
  final Widget smartPasteZone;

  const PurchaseHeader({
    super.key,
    required this.entryNo,
    required this.entryNavBox,
    required this.paymentMode,
    required this.onPaymentModeChanged,
    required this.supplierCtrl,
    required this.supplierFocus,
    required this.supplierLayer,
    required this.onSupplierChanged,
    required this.dueDate,
    required this.onDueDateChanged,
    required this.doneByCtrl,
    required this.doneByFocus,
    required this.doneByLayer,
    required this.onDoneByChanged,
    required this.gstMode,
    required this.onGstModeChanged,
    required this.date,
    required this.onDateChanged,
    required this.supInvDate,
    required this.onSupInvDateChanged,
    required this.supInvNoCtrl,
    required this.supInvNoFocus,
    this.isAutoGeneratedSupInv = false,
    this.isDuplicateSupInv = false,
    this.onSupInvNoChanged,
    required this.invTotalCtrl,
    required this.invTotalFocus,
    required this.formatSelector,
    required this.smartPasteZone,
  });

  @override
  Widget build(BuildContext context) {
    final c = AppColors.of(context);

    return Container(
      padding: const EdgeInsets.all(8),
      color: c.cardBg,
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Expanded(
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Row(children: [
                  _label(c, "Entry No:"),
                  entryNavBox,
                  const SizedBox(width: 10),
                  _radio(c, "Credit", 1, paymentMode, onPaymentModeChanged),
                  _radio(c, "Cash", 2, paymentMode, onPaymentModeChanged),
                  const SizedBox(width: 10),
                  _label(c, "Supplier:"),
                  _headerField(c, supplierCtrl, supplierFocus, width: 250, link: supplierLayer, onChanged: onSupplierChanged),
                  _smallIconBtn(Icons.add, () {
                    Provider.of<AppProvider>(context, listen: false).openSupplierRegistration();
                  }),
                  const SizedBox(width: 10),
                  _label(c, "Due Date:"),
                  _dateBox(context, c, dueDate, onDueDateChanged),
                  const SizedBox(width: 10),
                  _label(c, "Done By:"),
                  _headerField(c, doneByCtrl, doneByFocus, width: 100, link: doneByLayer, onChanged: onDoneByChanged),
                  const SizedBox(width: 10),
                  _radio(c, "Gst", 1, gstMode, onGstModeChanged),
                  _radio(c, "Non Gst", 2, gstMode, onGstModeChanged),
                ]),
                const SizedBox(height: 6),
                Row(children: [
                  _label(c, "Date:"),
                  _dateBox(context, c, date, (d) => onDateChanged(DateTime(d.year, d.month, d.day, date.hour, date.minute))),
                  const SizedBox(width: 5),
                  _timeBox(context, c, date, (t) => onDateChanged(DateTime(date.year, date.month, date.day, t.hour, t.minute))),
                  const SizedBox(width: 15),
                  _label(c, "Sup Inv Date:"),
                  _dateBox(context, c, supInvDate, onSupInvDateChanged),
                  const SizedBox(width: 20),
                  _label(c, "Sup Inv No:"),
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      _headerField(
                        c,
                        supInvNoCtrl, 
                        supInvNoFocus, 
                        width: isDuplicateSupInv || isAutoGeneratedSupInv ? 200 : 250,
                        bgColor: isDuplicateSupInv 
                            ? (c.isDark ? Colors.red.shade900.withValues(alpha: 0.3) : const Color(0xFFFFEBEE)) 
                            : (isAutoGeneratedSupInv ? (c.isDark ? Colors.blue.shade900.withValues(alpha: 0.3) : const Color(0xFFEFF6FF)) : null),
                        borderColor: isDuplicateSupInv 
                            ? Colors.red.shade400 
                            : (isAutoGeneratedSupInv ? Colors.blue.shade300 : null),
                        textColor: isDuplicateSupInv 
                            ? Colors.redAccent 
                            : (isAutoGeneratedSupInv ? Colors.blueAccent : null),
                        onChanged: (val) {
                          if (onSupInvNoChanged != null) onSupInvNoChanged!(val);
                        },
                      ),
                      if (isDuplicateSupInv) ...[
                        const SizedBox(width: 4),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 6),
                          decoration: BoxDecoration(
                            color: Colors.red.withValues(alpha: 0.15),
                            borderRadius: BorderRadius.circular(4),
                            border: Border.all(color: Colors.red.shade300),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(Icons.warning_amber_rounded, size: 12, color: Colors.red.shade400),
                              const SizedBox(width: 3),
                              Text("DUPLICATE", style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.red.shade400)),
                            ],
                          ),
                        ),
                      ] else if (isAutoGeneratedSupInv) ...[
                        const SizedBox(width: 4),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 6),
                          decoration: BoxDecoration(
                            color: Colors.blue.withValues(alpha: 0.15),
                            borderRadius: BorderRadius.circular(4),
                            border: Border.all(color: Colors.blue.shade200),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(Icons.south_west_rounded, size: 11, color: Colors.blue.shade400),
                              const SizedBox(width: 3),
                              Text("auto filled", style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.blue.shade400)),
                            ],
                          ),
                        ),
                      ],
                    ],
                  ),
                  const SizedBox(width: 20),
                  _label(c, "Inv Total:"),
                  _headerField(c, invTotalCtrl, invTotalFocus, width: 100, bgColor: c.isDark ? Colors.amber.shade900.withValues(alpha: 0.2) : const Color(0xFFFFFDE7), isNumeric: true),
                ]),
              ]),
            ),
          ),
          const SizedBox(width: 12),
          Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              formatSelector,
              const SizedBox(height: 6),
              smartPasteZone,
            ],
          ),
        ],
      ),
    );
  }

  Widget _label(AppThemeColors c, String t) => Padding(padding: const EdgeInsets.only(right: 6), child: Text(t, style: TextStyle(fontWeight: FontWeight.bold, fontSize: 11, color: c.secondaryText)));

  Widget _radio(AppThemeColors c, String label, int val, int group, Function(int) onChange) => Row(children: [
    SizedBox(
      width: 22,
      height: 22,
      child: Radio<int>(
        value: val,
        groupValue: group,
        onChanged: (v) => onChange(v!),
        visualDensity: const VisualDensity(horizontal: -4, vertical: -4),
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
      ),
    ),
    const SizedBox(width: 2),
    Text(label, style: TextStyle(fontSize: 11, color: c.primaryText)),
  ]);

  Widget _headerField(AppThemeColors c, TextEditingController ctrl, FocusNode fn, {double width = 150, LayerLink? link, Color? bgColor, Color? borderColor, Color? textColor, bool isNumeric = false, ValueChanged<String>? onChanged}) {
    Widget field = TextField(
      controller: ctrl,
      focusNode: fn,
      onChanged: onChanged,
      keyboardType: isNumeric ? const TextInputType.numberWithOptions(decimal: true) : null,
      style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: textColor ?? c.primaryText),
      decoration: InputDecoration(
        isDense: true,
        contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10),
        fillColor: bgColor ?? c.inputBg,
        filled: true,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(4), borderSide: BorderSide(color: borderColor ?? c.border)),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(4), borderSide: BorderSide(color: borderColor ?? c.border)),
      ),
    );

    if (link != null) {
      field = CompositedTransformTarget(link: link, child: field);
    }

    return SizedBox(width: width, child: field);
  }

  Widget _dateBox(BuildContext context, AppThemeColors c, DateTime dt, ValueChanged<DateTime> onPicked) => InkWell(
    onTap: () async {
      final d = await showAppDatePicker(context: context, initialDate: dt, firstDate: DateTime(2000), lastDate: DateTime(2100));
      if (d != null) onPicked(d);
    },
    child: Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      decoration: BoxDecoration(border: Border.all(color: c.border), borderRadius: BorderRadius.circular(4), color: c.inputBg),
      child: Row(children: [
        Text(DateFormat('dd/MM/yyyy').format(dt), style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: c.primaryText)),
        const SizedBox(width: 4),
        Icon(Icons.calendar_today, size: 12, color: c.secondaryText),
      ]),
    ),
  );

  Widget _timeBox(BuildContext context, AppThemeColors c, DateTime dt, ValueChanged<TimeOfDay> onPicked) => InkWell(
    onTap: () async {
      final t = await showTimePicker(context: context, initialTime: TimeOfDay.fromDateTime(dt));
      if (t != null) onPicked(t);
    },
    child: Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      decoration: BoxDecoration(border: Border.all(color: c.border), borderRadius: BorderRadius.circular(4), color: c.inputBg),
      child: Row(children: [
        Text(DateFormat('hh:mm a').format(dt), style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: c.primaryText)),
        const SizedBox(width: 4),
        Icon(Icons.access_time, size: 12, color: c.secondaryText),
      ]),
    ),
  );

  Widget _smallIconBtn(IconData icon, VoidCallback onTap) => IconButton(
    onPressed: onTap,
    icon: Icon(icon, size: 16, color: Colors.blue.shade400),
    padding: EdgeInsets.zero,
    constraints: const BoxConstraints(),
    splashRadius: 18,
  );
}
